// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAndTrim(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadAndTrim'](arg1, arg2, arg3, arg4);
}

export function EnsureFfmpeg() {
  return window['go']['main']['App']['EnsureFfmpeg']();
}

export function FetchMetadata(arg1) {
  return window['go']['main']['App']['FetchMetadata'](arg1);
}

export function FfmpegVersion() {
  return window['go']['main']['App']['FfmpegVersion']();
}

export function PickOutputPath(arg1) {
  return window['go']['main']['App']['PickOutputPath'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}
