// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {youtube} from '../models';

export function DownloadAndTrim(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function EnsureFfmpeg():Promise<string>;

export function FetchMetadata(arg1:string):Promise<youtube.Metadata>;

export function FfmpegVersion():Promise<string>;

export function PickOutputPath(arg1:string):Promise<string>;

export function Ping():Promise<string>;
